In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv(r'C:\Users\user\Datasets\Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
x=data.iloc[:,3:13].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y=data.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ct=ColumnTransformer([('on',OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
x=x[:,1:]
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
x[0]

array([0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
lb=LabelEncoder()
x[:,3]=lb.fit_transform(x[:,3])
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
x[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [17]:
x[771]

array([0.0, 0.0, 717, 1, 31, 4, 129722.57, 1, 0, 0, 41176.6], dtype=object)

In [18]:
x.shape

(10000, 11)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [20]:
x=sc.fit_transform(x)
x

array([[-0.57873591, -0.57380915, -0.32622142, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.57873591,  1.74273971, -0.44003595, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.57873591, -0.57380915, -1.53679418, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.57873591, -0.57380915,  0.60498839, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.72790383, -0.57380915,  1.25683526, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.57873591, -0.57380915,  1.46377078, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
x_train.shape

(8000, 11)

In [23]:
x_test.shape

(2000, 11)

In [24]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [27]:
model = Sequential()

In [29]:
model.add(Dense(input_dim=11,kernel_initializer='random_uniform',units=15,activation='relu'))

In [30]:
model.add(Dense(units=8,kernel_initializer='random_uniform',activation='relu'))

In [31]:
model.add(Dense(units=1,kernel_initializer='random_uniform',activation='sigmoid'))

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                180       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 128       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 317
Trainable params: 317
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
model.fit(x_train,y_train,epochs=20,batch_size=32)

Train on 8000 samples
Epoch 1/20
8000/8000 [==============================] - 2s 200us/sample - loss: 0.5434 - accuracy: 0.7939
Epoch 2/20
8000/8000 [==============================] - 1s 81us/sample - loss: 0.4315 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 1s 64us/sample - loss: 0.4240 - accuracy: 0.8006
Epoch 4/20
8000/8000 [==============================] - 1s 79us/sample - loss: 0.4173 - accuracy: 0.8266
Epoch 5/20
8000/8000 [==============================] - 0s 55us/sample - loss: 0.4125 - accuracy: 0.8313
Epoch 6/20
8000/8000 [==============================] - 0s 53us/sample - loss: 0.4083 - accuracy: 0.8328
Epoch 7/20
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4055 - accuracy: 0.8328
Epoch 8/20
8000/8000 [==============================] - 0s 52us/sample - loss: 0.4032 - accuracy: 0.8345
Epoch 9/20
8000/8000 [==============================] - 1s 76us/sample - loss: 0.4018 - accuracy: 0.8361
Epoch 10/20
8000/8000 [=========

In [35]:
y_pred=model.predict(x_test)
y_pred

array([[0.20362335],
       [0.2879587 ],
       [0.16966444],
       ...,
       [0.16564563],
       [0.14659539],
       [0.14108571]], dtype=float32)

In [36]:
y_pred=(y_pred>=0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.846

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1550,   45],
       [ 263,  142]], dtype=int64)