## Numpy

In [1]:
import numpy as np #https://numpy.org/install/


In [2]:
np.__version__

'1.19.5'

In [3]:
#Shape: is the shape of the numpy zero array. Dtype: is the datatype in numpy zeros. 
#It is optional. The default value is float64.

In [4]:
z=np.zeros(4)   
z

array([0., 0., 0., 0.])

In [5]:
#The most important object defined in NumPy is an N-dimensional array type called ndarray. 
#It describes the collection of items of the same type.

In [6]:
type(z) 

numpy.ndarray

In [7]:
#Make z store some array values 

In [8]:
z=np.array([1,7,8.9,8,0]) 
z

array([1. , 7. , 8.9, 8. , 0. ])

In [9]:
z[3] #check the value at index 3

8.0

In [10]:
type(z[2]) #check the type of value at index 2

numpy.float64

In [11]:
z=z.astype(int) #change it to integer

In [12]:
z

array([1, 7, 8, 8, 0])

In [13]:
#NumPy provides:	extension package to Python for multi-dimensional arrays

In [14]:
a=np.array([[12,4,5],[3,6,7]])  
a

array([[12,  4,  5],
       [ 3,  6,  7]])

In [15]:
#In NumPy the number of dimensions is referred to as rank. 
#ndmin specifies the minimum dimensions of resultant array. 

In [16]:
a.ndim

2

In [17]:
a[0]

array([12,  4,  5])

In [18]:
a.shape

(2, 3)

In [19]:
a.reshape(3,2)

array([[12,  4],
       [ 5,  3],
       [ 6,  7]])

In [20]:
a.reshape(6,1)

array([[12],
       [ 4],
       [ 5],
       [ 3],
       [ 6],
       [ 7]])

In [21]:
a.reshape(1,6)

array([[12,  4,  5,  3,  6,  7]])

In [22]:
z=a.reshape(1,2,3)

In [23]:
z

array([[[12,  4,  5],
        [ 3,  6,  7]]])

In [24]:
z.ndim

3

In [25]:
z.size

6

In [26]:
a=np.array([[2,5,6],[6,5,8],[8,9,5]])
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [27]:
a[1][2]

8

In [28]:
a[2][1]

9

## Pandas

In [29]:
import pandas as pd

In [30]:
mylist=[25,30,35,40]

### Series 

In [31]:
#A Pandas Series is like a column in a table.

#It is a one-dimensional array holding data of any type.

In [32]:
z=pd.Series(data=mylist)
z

0    25
1    30
2    35
3    40
dtype: int64

In [33]:
type(z)

pandas.core.series.Series

In [34]:
#we can assign different kinds of indexes instead od 0123

In [35]:
z=pd.Series(data=mylist,index=['A','B','C','D'])
z

A    25
B    30
C    35
D    40
dtype: int64

In [36]:
z['A']

25

In [37]:
pd.__version__

'1.0.1'

In [38]:
cric={"captain":"virat","opener":"rohit"} #even create a dictionary

In [39]:
ser=pd.Series(cric)

In [40]:
ser

captain    virat
opener     rohit
dtype: object

In [41]:
#perform operations of them

In [42]:
ser2=pd.Series([1,2,3,4],["USA","Germany","USSR","Japan"])
ser2

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [43]:
ser3=pd.Series([5,6,7,8],["USA","Germany","Italy","Japan"])
ser3

USA        5
Germany    6
Italy      7
Japan      8
dtype: int64

In [44]:
s=ser2+ser3
s

Germany     8.0
Italy       NaN
Japan      12.0
USA         6.0
USSR        NaN
dtype: float64

In [45]:
ser2*ser3

Germany    12.0
Italy       NaN
Japan      32.0
USA         5.0
USSR        NaN
dtype: float64

### Dataframes

In [46]:
employees=pd.DataFrame({"Empcode":[1,2,3,4],"Name":["Surya","Vinay","Mahathi","Sandeep"],'Occupation':['ML Engineer','AI Developer','ML ENgineer',"IoT Developer"],
                       'Date Of Join':['2018-01-25', '2018-01-26','2018-01-26','2018-01-27'],'Age': [25, 24,24,26]})
employees

Empcode     Name     Occupation Date Of Join  Age
0        1    Surya    ML Engineer   2018-01-25   25
1        2    Vinay   AI Developer   2018-01-26   24
2        3  Mahathi    ML ENgineer   2018-01-26   24
3        4  Sandeep  IoT Developer   2018-01-27   26

In [47]:
type(employees)

pandas.core.frame.DataFrame

In [48]:
employees.columns

Index(['Empcode', 'Name', 'Occupation', 'Date Of Join', 'Age'], dtype='object')

In [49]:
#change the name of column values

In [50]:
employees.columns=['empage', 'empDOJ', 'empcode', 'empName', 'empOccupation']

In [51]:
employees

empage   empDOJ        empcode     empName  empOccupation
0       1    Surya    ML Engineer  2018-01-25             25
1       2    Vinay   AI Developer  2018-01-26             24
2       3  Mahathi    ML ENgineer  2018-01-26             24
3       4  Sandeep  IoT Developer  2018-01-27             26

In [52]:
#The 'inplace=True' argument stands for the data frame has to make changes permanent

In [53]:
employees.rename(columns={'empcode':'empno'},inplace=True)

In [54]:
employees

empage   empDOJ          empno     empName  empOccupation
0       1    Surya    ML Engineer  2018-01-25             25
1       2    Vinay   AI Developer  2018-01-26             24
2       3  Mahathi    ML ENgineer  2018-01-26             24
3       4  Sandeep  IoT Developer  2018-01-27             26

In [55]:
employees.drop("empno",axis=1,inplace=True)

In [56]:
employees

empage   empDOJ     empName  empOccupation
0       1    Surya  2018-01-25             25
1       2    Vinay  2018-01-26             24
2       3  Mahathi  2018-01-26             24
3       4  Sandeep  2018-01-27             26

In [57]:
#removing multiple column using index numbers


In [58]:
employees.drop(employees.columns[[2,3]],axis=1)

empage   empDOJ
0       1    Surya
1       2    Vinay
2       3  Mahathi
3       4  Sandeep

In [59]:
#drop a row

In [60]:
employees.drop(2,axis=0)

empage   empDOJ     empName  empOccupation
0       1    Surya  2018-01-25             25
1       2    Vinay  2018-01-26             24
3       4  Sandeep  2018-01-27             26

In [61]:
#add a row

In [62]:
new={"surname":"B","empName":"Ram","empOccupation":"ML Engineer","empDOJ":"2018-01-25","empage":24,"empcity":"Hyderabad"}


In [63]:
employees.append(new,ignore_index=True)

empage      empDOJ     empName empOccupation    empcity surname
0       1       Surya  2018-01-25            25        NaN     NaN
1       2       Vinay  2018-01-26            24        NaN     NaN
2       3     Mahathi  2018-01-26            24        NaN     NaN
3       4     Sandeep  2018-01-27            26        NaN     NaN
4      24  2018-01-25         Ram   ML Engineer  Hyderabad       B

### Converting pandas into numpy array

In [64]:
z=employees.values
z

array([[1, 'Surya', '2018-01-25', 25],
       [2, 'Vinay', '2018-01-26', 24],
       [3, 'Mahathi', '2018-01-26', 24],
       [4, 'Sandeep', '2018-01-27', 26]], dtype=object)

In [65]:
z.ndim

2

In [66]:
z.size

16

In [67]:
z.shape

(4, 4)

In [68]:
type(z)

numpy.ndarray

In [69]:
z=pd.DataFrame(z)
z

0        1           2   3
0  1    Surya  2018-01-25  25
1  2    Vinay  2018-01-26  24
2  3  Mahathi  2018-01-26  24
3  4  Sandeep  2018-01-27  26